### ISSUE TITLE
Roadmap: Public Pipeline Metrics

### ISSUE THREAD

**Issue by Kadino** [o3de/sig-testing#62]
### Summary:
Expose a metrics summary accessible by all public contributors. This should be a simple HTML dashboard, which is generated by scripts in the O3DE repo.

### What is the relevance of this feature?
Helps contributors understand the health of automated build-and-test across O3DE's many CI pipelines, and where to contribute at a glance.

```[tasklist]
### Tasks
- [ ] https://github.com/o3de/sig-testing/issues/34
- [ ] https://github.com/o3de/sig-testing/pull/69
- [ ] (RFC followup work TBD)
```
