### ISSUE TITLE
Roadmap: In-Game Test Automation

### ISSUE THREAD

**Issue by Kadino** [o3de/sig-testing#63]
### Summary:
Tools to simplify creating automated tests which execute inside the game engine, such as the deployable Game and Server executables.

### What is the relevance of this feature?
Helps O3DE contributors write tests for in-game (in-engine) functionality, separate from the Editor. Helps teams using O3DE write tests for their own production code.

```[tasklist]
### Tasks
- [ ] https://github.com/o3de/sig-testing/issues/20
- [ ] https://github.com/o3de/sig-testing/pull/66
- [ ] (RFC followup work TBD)
```
