### ISSUE TITLE
Roadmap: Intermittent Failure Notifications

### ISSUE THREAD

**Issue by Kadino** [o3de/sig-testing#64]
### Summary:
Use metrics on historical test failure rates to send automated notifications before intermittent failures reach a critical mass of instability. A dashboard should also be available.

### What is the relevance of this feature?
Provides SIGs awareness of any infrequent but repeated failures in tests which they maintain. When delivered, SIGs should be better prompted to take early action before intermittent failure rates rise critically high.

```[tasklist]
### Tasks
- [ ] o3de/sig-testing#43
- [ ] https://github.com/o3de/sig-testing/issues/62 (blocking prerequisite)
- [ ] (RFC followup work TBD)
```
